### PR TITLE
document using nix flake

### PR DESCRIPTION
**Pull request by ghost**
Thank you for creating this flake!
It saved me hours.

I could not run airflow in this flake using `nix-shell shell.nix`.

It simply printed:
```
🔨 Welcome to devshell

[general commands]

  menu - prints this menu
```

I could run `nixFlakes shell` and then execute `airflow` commands.

### CODE REVIEW

**Comment by GTrunSec** [comment]
Thanks for your PR.

Actually, the nix-shell comes from flake-compat for the stable version of nix. I prefer to use `nix develop` instead. I don't know what is `nixFlakes` from where. Maybe you can add `nix develop` `nixFlakes` `nix-shell` all in README that would be enough.

**Comment by ghost** [comment]
Sounds good, I'll give that a try!

>  I don't know what is nixFlakes from where

I stole that shell alias from the [NixOS' wiki ](https://nixos.wiki/wiki/Flakes)on using flakes in the context of stable nix.

**Comment by ghost** [comment]
Hmm, when I try `nix develop` followed by `airflow` I see this:
```
[devshell]$ airflow
The program 'airflow' is not in your PATH. It is provided by several packages.
You can make it available in an ephemeral shell by typing one of the following:
  nix-shell -p apache-airflow
  nix-shell -p python38Packages.apache-airflow
```
Any tips on what I might be doing wrong?

**Comment by GTrunSec** [comment]
please check CI https://github.com/GTrunSec/airflow2nix/runs/5100268969?check_suite_focus=true#step:9:1 log.
I have no idea, you can try git fetch && git pull as well.

**Comment by ghost** [comment]
> Any tips on what I might be doing wrong?

I was missing the appropriate flags to `nix`.
I updated the README to reflect what you need to execute.
I also tested on my nixOS machine.

**Comment by GTrunSec** [comment]
Thanks, Could you please add the `nix develop and nix-shell` as well? also, we don't need the flag of `-Lv` in the production environment and use `nix develop --print-build-logs ` instead.

```
nix develop --print-build-logs  (for direnv and develop env)
nix-shell (native command for flake compact)
nix-build (./result/bin/airflow)
nix run .#airflow-release -- info (for nix app)
```

**Comment by ghost** [comment]
> Thanks, Could you please add the nix develop and nix-shell as well? 

Thanks for the feedback @GTrunSec! Unfortunately I have other projects that have come up so I will have to stop working on this.

**Comment by GTrunSec** [comment]
it's ok, let me update this information. thanks for your PR

**Pull request closed without merging**
